// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormController from "./form_controller"
application.register("form", FormController)

import ListController from "./list_controller"
application.register("list", ListController)

import PresenterController from "./presenter_controller"
application.register("presenter", PresenterController)
